# Generated by Django 3.2.25 on 2025-06-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('blog_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Like History',
                'verbose_name_plural': 'Like Histories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('blog_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Read History',
                'verbose_name_plural': 'Read Histories',
                'managed': False,
            },
        ),
    ]
