# Generated by Django 3.2.25 on 2025-06-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_likehistory_readhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
